language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

matrix:
  exclude:
    - php: hhvm
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"

sudo: false

before_script:
  - composer --prefer-source --dev ${COMPOSER_FLAGS} update

script: bin/phpunit

notifications:
  irc: "irc.freenode.org#fsi-open"
